"""empty message

Revision ID: 00b2942bd2b4
Revises: 396470f04c5a
Create Date: 2020-01-25 17:32:04.628666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b2942bd2b4'
down_revision = '396470f04c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=64), nullable=True))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('cars', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
