"""empty message

Revision ID: 013e38af9c45
Revises: d767c15d6647
Create Date: 2020-02-10 20:52:40.363211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '013e38af9c45'
down_revision = 'd767c15d6647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_capacity_height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('used_capacity_length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('used_capacity_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('used_capacity_width', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.drop_column('used_capacity_width')
        batch_op.drop_column('used_capacity_weight')
        batch_op.drop_column('used_capacity_length')
        batch_op.drop_column('used_capacity_height')

    # ### end Alembic commands ###
