"""empty message

Revision ID: 1ccf70a60076
Revises: 6af9963230ca
Create Date: 2020-01-25 01:11:13.210392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ccf70a60076'
down_revision = '6af9963230ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('capacity_length', sa.Float(), nullable=True),
    sa.Column('capacity_weight', sa.Float(), nullable=True),
    sa.Column('capacity_width', sa.Float(), nullable=True),
    sa.Column('capacity_height', sa.Float(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_cars_author_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cars'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
