"""empty message

Revision ID: 204a671eb82d
Revises: 81fd45962170
Create Date: 2020-01-26 12:15:12.289437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204a671eb82d'
down_revision = '81fd45962170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('free_capacity_height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('free_capacity_length', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('free_capacity_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('free_capacity_width', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.drop_column('free_capacity_width')
        batch_op.drop_column('free_capacity_weight')
        batch_op.drop_column('free_capacity_length')
        batch_op.drop_column('free_capacity_height')

    # ### end Alembic commands ###
