"""empty message

Revision ID: 237bf78fe76d
Revises: 721f7bdf31e9
Create Date: 2020-01-21 19:31:35.821615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237bf78fe76d'
down_revision = '721f7bdf31e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('info', sa.Text(), nullable=True))
    op.add_column('items', sa.Column('length', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('items', sa.Column('width', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'items', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'width')
    op.drop_column('items', 'weight')
    op.drop_column('items', 'length')
    op.drop_column('items', 'info')
    op.drop_column('items', 'height')
    op.drop_column('items', 'author_id')
    # ### end Alembic commands ###
