"""empty message

Revision ID: 3451b6d87f7f
Revises: 0202afbccde3
Create Date: 2019-12-29 22:54:07.600067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3451b6d87f7f'
down_revision = '0202afbccde3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_link', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_link')
    # ### end Alembic commands ###
