"""empty message

Revision ID: 396470f04c5a
Revises: d3da978db669
Create Date: 2020-01-25 14:21:27.791609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396470f04c5a'
down_revision = 'd3da978db669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('localization_counter', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.drop_column('localization_counter')

    # ### end Alembic commands ###
