"""empty message

Revision ID: 4d8489f48569
Revises: d3909a4beeb3
Create Date: 2020-01-22 19:24:36.500569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8489f48569'
down_revision = 'd3909a4beeb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])

    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.drop_column('title')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
