"""empty message

Revision ID: 54b3f88f24dc
Revises: 079241709a41
Create Date: 2020-01-02 19:24:48.857024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b3f88f24dc'
down_revision = '079241709a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('localization', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'localization')
    # ### end Alembic commands ###
