"""empty message

Revision ID: 56384f77c65b
Revises: db5e6bd8543f
Create Date: 2019-12-24 13:46:57.518293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56384f77c65b'
down_revision = 'db5e6bd8543f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###
