"""empty message

Revision ID: 58007c143eba
Revises: 00b2942bd2b4
Create Date: 2020-01-25 17:57:14.095511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58007c143eba'
down_revision = '00b2942bd2b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_localization', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('next_localization1', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('next_localization2', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('next_localization3', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('next_localization4', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('next_localization5', sa.String(length=64), nullable=True))
        batch_op.drop_column('destination')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('next_localization5')
        batch_op.drop_column('next_localization4')
        batch_op.drop_column('next_localization3')
        batch_op.drop_column('next_localization2')
        batch_op.drop_column('next_localization1')
        batch_op.drop_column('end_localization')

    # ### end Alembic commands ###
