"""empty message

Revision ID: 6af9963230ca
Revises: 6e2b7fb28081
Create Date: 2020-01-22 19:31:06.331590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af9963230ca'
down_revision = '6e2b7fb28081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_items_author_id_users'), 'users', ['author_id'], ['id'])

    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=64), nullable=True))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_roles_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_roles_name'), type_='unique')

    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.drop_column('title')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_items_author_id_users'), type_='foreignkey')

    # ### end Alembic commands ###
