"""empty message

Revision ID: 721f7bdf31e9
Revises: c060a4bbaba0
Create Date: 2020-01-11 15:11:44.917444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721f7bdf31e9'
down_revision = 'c060a4bbaba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dangers', sa.Column('position_center', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dangers', 'position_center')
    # ### end Alembic commands ###
