"""empty message

Revision ID: 81fd45962170
Revises: 38a0f7bbfbbb
Create Date: 2020-01-25 20:52:06.366666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81fd45962170'
down_revision = '38a0f7bbfbbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_journeys_car_id_cars'), 'cars', ['car_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_journeys_car_id_cars'), type_='foreignkey')
        batch_op.drop_column('car_id')

    # ### end Alembic commands ###
