"""empty message

Revision ID: 838f208fbff9
Revises: 56384f77c65b
Create Date: 2019-12-28 16:25:07.552122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838f208fbff9'
down_revision = '56384f77c65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('company', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'location')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'company')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
