"""empty message

Revision ID: 8dc884f36d94
Revises: 204a671eb82d
Create Date: 2020-02-10 20:11:57.802169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc884f36d94'
down_revision = '204a671eb82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('position_y', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('position_z', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.drop_column('position_z')
        batch_op.drop_column('position_y')
        batch_op.drop_column('position_x')

    # ### end Alembic commands ###
