"""empty message

Revision ID: 99b200dd6db9
Revises: 3451b6d87f7f
Create Date: 2019-12-29 23:47:16.690806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b200dd6db9'
down_revision = '3451b6d87f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_link', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
