"""empty message

Revision ID: b42be3f2ed5f
Revises: d87b192daa53
Create Date: 2020-01-22 19:07:16.412137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42be3f2ed5f'
down_revision = 'd87b192daa53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'items', 'users', ['author_id'], ['id'])
    op.add_column('journeys', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journeys', 'name')
    op.drop_constraint(None, 'items', type_='foreignkey')
    # ### end Alembic commands ###
