"""empty message

Revision ID: d3da978db669
Revises: 1ccf70a60076
Create Date: 2020-01-25 14:12:29.704115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3da978db669'
down_revision = '1ccf70a60076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_point_positions', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('next_point_positions1', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('next_point_positions2', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('next_point_positions3', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('next_point_positions4', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('next_point_positions5', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('start_point_positions', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.drop_column('start_point_positions')
        batch_op.drop_column('next_point_positions5')
        batch_op.drop_column('next_point_positions4')
        batch_op.drop_column('next_point_positions3')
        batch_op.drop_column('next_point_positions2')
        batch_op.drop_column('next_point_positions1')
        batch_op.drop_column('end_point_positions')

    # ### end Alembic commands ###
