"""empty message

Revision ID: d767c15d6647
Revises: 8dc884f36d94
Create Date: 2020-02-10 20:28:25.367749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd767c15d6647'
down_revision = '8dc884f36d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_x', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('position_y', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('position_z', sa.Float(), nullable=True))

    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.drop_column('position_x')
        batch_op.drop_column('position_z')
        batch_op.drop_column('position_y')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journeys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_y', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('position_z', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('position_x', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('position_z')
        batch_op.drop_column('position_y')
        batch_op.drop_column('position_x')

    # ### end Alembic commands ###
